import { useState, useEffect } from 'react';
import { fetchSavedReports } from '../api';
import ReactMarkdown from 'react-markdown';
import { Sparkles, Calendar, User, FileText, ChevronDown, ChevronUp } from 'lucide-react';
import toast from 'react-hot-toast';

export function Reports() {
  const [reports, setReports] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    try {
      setIsLoading(true);
      const data = await fetchSavedReports();
      setReports(data || []);
    } catch (error: any) {
      toast.error(error.message || 'Failed to load reports');
    } finally {
      setIsLoading(false);
    }
  };

  const toggleExpand = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full min-h-[400px]">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-brand-primary"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in pb-8">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-gray-900 tracking-tight mt-1 flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-brand-primary" />
            Saved AI Reports
          </h1>
          <p className="text-sm text-gray-500 mt-1">Review historical operational and financial reports generated by AI.</p>
        </div>
      </div>

      <div className="grid gap-4">
        {reports.length === 0 ? (
          <div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-200 text-center">
            <div className="w-16 h-16 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-4">
              <FileText className="w-8 h-8 text-gray-400" />
            </div>
            <h3 className="text-lg font-bold text-gray-900 mb-2">No Reports Saved Yet</h3>
            <p className="text-gray-500 text-sm">Generate and save an AI report from the Dashboard to see it here.</p>
          </div>
        ) : (
          reports.map((report) => (
            <div key={report.id} className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden transition-all duration-200">
              <div 
                className="p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 cursor-pointer hover:bg-gray-50"
                onClick={() => toggleExpand(report.id)}
              >
                <div className="space-y-1">
                  <h3 className="font-bold text-gray-900 text-lg">{report.title}</h3>
                  <div className="flex flex-wrap items-center gap-4 text-xs font-medium text-gray-500">
                    <span className="flex items-center gap-1">
                      <Calendar className="w-3.5 h-3.5" />
                      {new Date(report.createdAt).toLocaleString()}
                    </span>
                    <span className="flex items-center gap-1">
                      <User className="w-3.5 h-3.5" />
                      Saved by: {report.generatedBy}
                    </span>
                  </div>
                </div>
                <div>
                  {expandedId === report.id ? (
                    <ChevronUp className="w-5 h-5 text-gray-400" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-400" />
                  )}
                </div>
              </div>
              
              {expandedId === report.id && (
                <div className="p-6 border-t border-gray-100 bg-gray-50/50">
                  <div className="prose prose-sm sm:prose-base prose-indigo max-w-none text-gray-800 bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
                    <ReactMarkdown>{report.content}</ReactMarkdown>
                  </div>
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
}
