"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const submodules_1 = require("../controllers/submodules");
const router = (0, express_1.Router)();
router.get("/accountLedgers/export/pdf", submodules_1.exportLedgerPdf);
router.get("/branches", submodules_1.getBranches);
router.post("/branches", submodules_1.createBranches);
router.get("/products", submodules_1.getProducts);
router.post("/products", submodules_1.createProducts);
router.get("/inventoryItems", submodules_1.getInventoryitems);
router.post("/inventoryItems", submodules_1.createInventoryitems);
router.put("/inventoryItems/:id/assign", submodules_1.assignInventoryitem);
router.get("/payments", submodules_1.getPayments);
router.post("/payments", submodules_1.createPayments);
router.get("/kycDocuments", submodules_1.getKycdocuments);
router.post("/kycDocuments", submodules_1.createKycdocuments);
router.put("/kycDocuments/:id/status", submodules_1.updateKycStatus);
router.get("/supportTickets", submodules_1.getSupporttickets);
router.post("/supportTickets", submodules_1.createSupporttickets);
router.put("/supportTickets/:id", submodules_1.updateSupporttickets);
router.get("/communicationLogs", submodules_1.getCommunicationlogs);
router.post("/communicationLogs", submodules_1.createCommunicationlogs);
router.get("/auditLogs", submodules_1.getAuditlogs);
router.post("/auditLogs", submodules_1.createAuditlogs);
router.get("/operationsTasks", submodules_1.getOperationstasks);
router.post("/operationsTasks", submodules_1.createOperationstasks);
router.get("/appraisals", submodules_1.getAppraisals);
router.post("/appraisals", submodules_1.createAppraisals);
router.get("/commissions", submodules_1.getCommissions);
router.post("/commissions", submodules_1.createCommissions);
router.get("/arrearsRecords", submodules_1.getArrearsrecords);
router.post("/arrearsRecords", submodules_1.createArrearsrecords);
router.get("/accountLedgers", submodules_1.getAccountledgers);
router.post("/accountLedgers", submodules_1.createAccountledgers);
router.get("/journalVouchers", submodules_1.getJournalvouchers);
router.post("/journalVouchers", submodules_1.createJournalvouchers);
router.get("/journalVouchers/export/pdf", submodules_1.exportJournalVoucherPdf);
router.get("/journalVouchers/:id/export/pdf", submodules_1.exportJournalVoucherPdf);
exports.default = router;
//# sourceMappingURL=submodules.js.map